#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-timers
Version  : 4.1.1
Release  : 7
URL      : https://rubygems.org/downloads/timers-4.1.1.gem
Source0  : https://rubygems.org/downloads/timers-4.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-hitimes
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
Timers
======
[![Gem Version](https://badge.fury.io/rb/timers.png)](http://rubygems.org/gems/timers)
[![Build Status](https://secure.travis-ci.org/celluloid/timers.png?branch=master)](http://travis-ci.org/celluloid/timers)
[![Code Climate](https://codeclimate.com/github/celluloid/timers.png)](https://codeclimate.com/github/celluloid/timers)
[![Coverage Status](https://coveralls.io/repos/celluloid/timers/badge.png?branch=master)](https://coveralls.io/r/celluloid/timers)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n timers-4.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-timers.gemspec

%build
gem build rubygem-timers.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
timers-4.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/timers-4.1.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/.coveralls.yml
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/AUTHORS.md
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/events.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/group.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/timer.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/lib/timers/wait.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/cancel_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/events_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/every_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/group_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/performance_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/strict_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/spec/timeout_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/timers-4.1.1/timers.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/timers-4.1.1.gemspec
